### ISSUE TITLE
Use toast notif instead of page redirection after subscribing

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#103]
![image](https://user-images.githubusercontent.com/61826995/189685933-d5aac456-c50b-4c9d-9042-ac2177568e58.png)

A simple toast notif on the upper right most part will do
<img width="301" alt="Screen Shot 2022-09-12 at 10 52 42 PM" src="https://user-images.githubusercontent.com/61826995/189686111-2fcbcf2a-ef90-4cbd-be1d-7a23875b861d.png">

**Comment by ricoz** [comment]
Ano updates kaini?

**Comment by EAdornado** [comment]
New website layout, Closing this issue since it will not be applicable for the new layout.
