### ISSUE TITLE
Add Lore for 1 of 1's 

### ISSUE THREAD

**Issue by EAdornado** [mgguild/msw-website#160]
Add pop up where it shows the lore of the character clicked. (Reveal one by one when our marketing team has already posted their lores)

Lores:

1/1 -Frozbyte
Class- Elemental
Lore: Hatched from an Elemental egg, but unfortunately, in a different... frozen world. The Fiery Elemental struggled to live, but managed to adapt its magic to match the surroundings. Years past, it thrived in the frozen tombs, but every now and then, a call from the magma chambers called to it. as if mourning of its loss.
1/1 -The First One, Adamus Primis
Class- Magitech
Lore: An ancient machine that seemingly hallow inside. it pre-dates most of digger history, but has the technology even the smartest engineer could not know. It gleams like it is a soul trapped in a stony rune-filled shell, struggling to break free.
1/1 -Lich King, Laudanum
Class- Plague Doctor
Lore: Experimenting with corpses, breathing new life, and the destroying it. It does not satisfy him. So he had an idea, flesh is unreliable, what about metal, cloth, leather, and ... magic? To give him a new form, the Lich King.
1/1 -Fraxure, The Axe
Class- Berserker
Lore: Frozen in Ice, he predates even the oldest digger fossils. He is the peak form of survivalist of all digger kind.
1/1 -The Meteor’s Lover
Class- Musketeer
Lore: It is not the meteor that corrupted him, it is his obsession with it. He actively sabotages any expeditions to the meteor, acting as if a double spy. A protector of the meteor.
1/1 -Agatha Badeux, The Arbalest
Class- Archer
Lore: After serving the Archer corps, the arbalest ventured on her own, disbanding bandits that plagued the surface and entrance levels. It is a deed unnoticed by the digger population. but it is a noble act indeed.
1/1 -Gerard, The Old and Honorable
Class- Knight
Lore: After all the wars and battles, he was put to the test upon entering the caves. Grueling skirmishes, room after room, floor after floor, each has given him a medal.
1/1 -Dominion, Baraqiel Kezef Zakum
Class- Vicar
Lore: Wonder who or what the digger’s worship? Here’s 1% of their god’s power.
1/1 -Twelve, the Voidmancer
Class- Wizard
Lore: After witnessing the endless void and the creatures that resides within it, She trained her magic endlessly, reaching a rank not claimed by any other wizards, the Voidmancer. For the sole purpose of destroying all levels of the cave, in case the void creatures decides to come out.
1/1 -Sgt. Jutta Hohenheim
Class- Engineer
Lore: Curious to see beyond the void’s black abyss, He crafted an armor impervious to “nothingness”, conditioned his body to withstand thirst and hunger, and his mind to eternity, before jumping off the cliff of the void.
1/1 - Deacon Johnson, The Devil Dealer
Class- Artillery
Lore: This artillery has struck a deal with the devil. The power to win every duel.
1/1 - Alexandrus, oblitus aviam heros
Class- Dark Knight
Lore: A kind, powerful hero that lived in eons past, he is the epitome of justice and equality. His form is given as a temporary gift by High Vicars to feel sane even for just 1 day, before being thrown back into darkness.

**Comment by ricoz** [comment]
Ano updates digdi? Feb 27 pa baga ini

**Comment by EAdornado** [comment]
Will not be applicable for the new layout of the website
