### ISSUE TITLE
Change social media links

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#342]
<img width="401" alt="Screenshot 2024-03-04 at 10 58 45 AM" src="https://github.com/mgguild/msw-website/assets/61826995/d36a32e2-5ed1-4293-a563-8cc63f8bc382">

Facebook: https://www.facebook.com/MetaSagaWarriorsOfficial
Instagram: https://www.instagram.com/metasagawarriors/?hl=en
Discord: https://discord.com/invite/5mDJmv7su3
Youtube: https://www.youtube.com/@metasagawarriors
Medium: https://medium.com/@metasagawarriors

Remove Reddit and Add X

X: https://twitter.com/metasagawarrior

**Comment by justinbalaguer** [comment]
gamitin ko muna old twitter logo may issue ako sa fontawesome atm.
