### ISSUE TITLE
Add a close button in this modal

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#349]
<img width="577" alt="Screenshot 2024-03-04 at 12 46 35 PM" src="https://github.com/mgguild/msw-website/assets/61826995/b66306d2-3780-406c-b434-7e397d673262">

**Comment by Buko-pie** [comment]
sa profile page yan @swengr-janan? ginawa kong unclosable ta need mag login para ma gamit ang page

**Comment by swengr-janan** [comment]
iyo jambs kaso dead end kaya, wara sya madumanan kung abo nya man mag log in. at least close button paduman sa digger list nalang @Buko-pie
