### ISSUE TITLE
Fix error regarding SDK

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#350]
<img width="1440" alt="Screenshot 2024-03-04 at 12 47 11 PM" src="https://github.com/mgguild/msw-website/assets/61826995/b8c560c1-652a-47b3-918e-881913bce444">

**Comment by justinbalaguer** [comment]
nag pull kana latest?

**Comment by justinbalaguer** [comment]
pa open na lang ulit pag ganun pa din pero resolve na to sa latest update
