### ISSUE TITLE
Do not display BUY button if wallet isn't connected yet. Display Connect Wallet instead

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#351]
<img width="1182" alt="Screenshot 2024-03-04 at 12 49 39 PM" src="https://github.com/mgguild/msw-website/assets/61826995/65a0af86-9f0c-471c-aa7e-873224e6d04a">

**Comment by justinbalaguer** [comment]
connected wallet na yan pag ganyan. tlgang naga reset lang si login sa website pero si wallet dae man sya na disconnect
