### ISSUE TITLE
Apply these informative text in the Membership page

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#399]
**Premium Membership Tiers**
3 months
9235.22 MGG

6 months
16632.09 MGG

12 months
23147.32 MGG

**How to Obtain Premium Membership**
1. Buy MGG on [SparkSwap](https://sparkswap.finance/) or [PancakeSwap](https://pancakeswap.finance/)
2. Buy premium membership here
3. After buying, your premium membership status will be set to Active
4. Log into MetaSaga Warriors Game
5. Enjoy premium membership perks in-game

**Comment by justinbalaguer** [comment]
#396 

These informative texts are applied already, naka hide lang atm kaya wala open for now ang issue #396 

closing...
