### ISSUE TITLE
Infinite loading on Buy button

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#406]
<img width="1312" alt="Screenshot 2024-05-21 at 2 34 29 PM" src="https://github.com/mgguild/msw-website/assets/61826995/37037fc3-ca10-462c-b9be-09d3ee9ed84d">

**Comment by justinbalaguer** [comment]
@swengr-janan na try mo sa branch ni jambs if arog pa din kaan?

**Comment by swengr-janan** [comment]
membership-contract-intrf-plyfb digdi na branch jazz?  iyo kahapon tig try ko arog pa kaan

pero kang sa pc na ni jambs nag gana man
