### ISSUE TITLE
Add proper spacing

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/msw-website#63]
<img width="706" alt="Screen Shot 2022-05-16 at 8 58 51 PM" src="https://user-images.githubusercontent.com/61826995/168597953-47f79ffe-be47-4c9e-9d46-b155cf514ede.png">

**Comment by vkth** [comment]
@swengr-janan sir ask ko lang po sa anong view po pala ito? and ano po yung dimensions?

**Comment by swengr-janan** [comment]
@vkth  sa tablet view 845x623
